[project]
name = "docvet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alberto Nieto", email = "alberto.codes.dev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
docvet = "docvet:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
